//! Known Answer Test (KAT) vectors for AES-GEM interoperability.
//!
//! Reads kat.json (generated by the Go reference implementation) and
//! verifies that the Rust implementation produces identical output.

use aes::Aes256;
use aes_gem::aead::{AeadInOut, KeyInit};
use aes_gem::AesGem;
use cipher::array::Array;
use cipher::consts::{U12, U13, U14, U15, U16, U32};
use serde::Deserialize;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct KatFile {
    test_groups: Vec<TestGroup>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct TestGroup {
    #[allow(dead_code)]
    test_group_id: usize,
    tag_bits: usize,
    tests: Vec<TestCase>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct TestCase {
    #[allow(dead_code)]
    test_id: usize,
    description: String,
    key: String,
    nonce: String,
    plaintext: String,
    aad: String,
    ciphertext: String,
    tag: String,
}

fn decode_hex(s: &str) -> Vec<u8> {
    if s.is_empty() {
        return Vec::new();
    }
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

/// Encrypt with the given tag size and return (ciphertext, tag).
fn encrypt_detached<T: aes_gem::TagSize>(
    key: &[u8],
    nonce: &[u8],
    pt: &[u8],
    aad: &[u8],
) -> (Vec<u8>, Vec<u8>) {
    let key: [u8; 32] = key.try_into().unwrap();
    let nonce: Array<u8, U32> = nonce.try_into().unwrap();
    let cipher = AesGem::<Aes256, T>::new(&key.into());
    let mut buf = pt.to_vec();
    let tag = cipher
        .encrypt_inout_detached(&nonce, aad, (&mut buf[..]).into())
        .expect("encryption failed");
    (buf, tag.to_vec())
}

/// Decrypt with the given tag size and return plaintext.
fn decrypt_detached<T: aes_gem::TagSize>(
    key: &[u8],
    nonce: &[u8],
    ct: &[u8],
    aad: &[u8],
    tag_bytes: &[u8],
) -> Vec<u8> {
    let key: [u8; 32] = key.try_into().unwrap();
    let nonce: Array<u8, U32> = nonce.try_into().unwrap();
    let tag: Array<u8, T> = tag_bytes.try_into().unwrap();
    let cipher = AesGem::<Aes256, T>::new(&key.into());
    let mut buf = ct.to_vec();
    cipher
        .decrypt_inout_detached(&nonce, aad, (&mut buf[..]).into(), &tag)
        .expect("decryption failed");
    buf
}

/// Dispatch to the correct generic tag-size instantiation.
fn run_test_case(tag_bits: usize, tc: &TestCase) {
    let key = decode_hex(&tc.key);
    let nonce = decode_hex(&tc.nonce);
    let pt = decode_hex(&tc.plaintext);
    let aad = decode_hex(&tc.aad);
    let want_ct = decode_hex(&tc.ciphertext);
    let want_tag = decode_hex(&tc.tag);

    macro_rules! check {
        ($tag_ty:ty) => {{
            let (ct, tag) = encrypt_detached::<$tag_ty>(&key, &nonce, &pt, &aad);
            assert_eq!(ct, want_ct, "ciphertext mismatch: {}", tc.description);
            assert_eq!(tag, want_tag, "tag mismatch: {}", tc.description);
            let got_pt = decrypt_detached::<$tag_ty>(&key, &nonce, &want_ct, &aad, &want_tag);
            assert_eq!(got_pt, pt, "plaintext mismatch: {}", tc.description);
        }};
    }

    match tag_bits {
        96 => check!(U12),
        104 => check!(U13),
        112 => check!(U14),
        120 => check!(U15),
        128 => check!(U16),
        _ => panic!("unsupported tag size: {} bits", tag_bits),
    }
}

#[test]
fn kat_vectors() {
    let data = std::fs::read_to_string("../../kat.json").expect("read kat.json");
    let kat: KatFile = serde_json::from_str(&data).expect("parse kat.json");

    let mut total = 0;
    for group in &kat.test_groups {
        for tc in &group.tests {
            run_test_case(group.tag_bits, tc);
            total += 1;
        }
    }
    eprintln!("Verified {} KAT vectors", total);
}
